### ISSUE TITLE
所以能否使用Windows系统运行此项目呢？

### ISSUE THREAD

**Issue by 1578339936** [captain686/young-study#7]

**Comment by captain686** [comment]
可以windows运行，但是需要更改机器人版本，如果本地运行的话可以把代理部分去掉，如果需要本地版本我可以上传此版本，windows运行不建议采用docker

**Comment by 1578339936** [comment]
> 

已经自己修改使用了，感谢开发者专门去掉代理

**Comment by 1578339936** [comment]
代理问题导致无法正常生成截图。。。还是麻烦您上传下本地版吧，谢谢
